# Generated by Django 5.0.2 on 2024-06-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='patronymic',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role_id',
            field=models.IntegerField(default='0'),
        ),
    ]
