# Generated by Django 5.0.2 on 2024-06-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_content', '0002_alter_users_patronymic_alter_users_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='kind',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='schedule_id',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='schedule_id',
            new_name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='appointment_duration',
        ),
        migrations.AlterField(
            model_name='users',
            name='patronymic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
