# Generated by Django 5.0.2 on 2024-06-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_content', '0003_rename_kind_appointments_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
