# Generated by Django 5.0.2 on 2024-06-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_content', '0004_alter_events_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='duration',
            field=models.DurationField(),
        ),
    ]
